### ISSUE TITLE
Post Here If You want to Apply For Staff!

### ISSUE THREAD

**Issue by PinoyLifeCraftModerator** [PinoyLifeCraft/Pinoy-LifeCraft-Forums#24]
***[Want to apply for staff? Follow these form and type it Here on This Issue!]***

**-Name/Ign:**

**-What Rank are you applying for?** ***(1 Helper, 3 Builders)***

**-Reason :**

**-Do you have experience on being a staff?***

***[More Information]***

**-Tell us about Yourself :** ***(please add your age, name)***

***[Situations and Other stuff]***

**-What would be your action if there's a troublemaker?**

**-If he/she is a really close friend?**

**-Whats your status? or How long do you stay online?**

**-Are you friendly?**

Note : Still "Lacking of Information?", kindly ask.
Mentions : @PinoyLifeCraft
Mentions : @PinoyLifeCraftModerator
Mentions : @Kaoruuu

Note : We will not be accepting applications if not commenting your applications here!

![f83ac7206f76e5710215d4da32436776_1349x384](https://cloud.githubusercontent.com/assets/24989412/22970091/cd99a6c4-f3ab-11e6-8d31-bfb81d4648f4.png)

**Comment by Kaoruuu** [comment]
*giggles*

**Comment by PinoyLifeCraftModerator** [comment]
***giggles***

**Comment by Neil09to** [comment]
Name:Neil09
Can i apply to be a good Builder?
I want to be a Builder beacause ill dont try do be a staff i help another people in this server and ill banned 
a abusing players and Hackers in 10 years 
My Real Name is Neilivan Garcia my age is 10 years old 
Ill Banned all the TroubleMaker in 2 hours beacause he are abusing players
yes my freinds is many he/she 
im staying online EveryDay
im freindly beacause im so many freind there are so freindly to me

**Comment by Neil09to** [comment]
Name:Neil09
Can i apply to be a good Builder?
I want to be a builder beacause ill dont try to be a staff i help another people in this server and ill banned
a abusing players and hackers in 10 years
My Real Name is Neilivan Garcia my age is 10 years old
ill banned all the troublemaker in 2 hours
yes my freinds is many he/she
im staying online everyday
im freindly beacause im so many freind there are so freindly to me.

**Comment by Neil09to** [comment]
kaoru ok na ba ang format?

**Comment by Neil09to** [comment]
wews

**Comment by Neil09to** [comment]
Name:Neil09
Can I apply to be a good Builder?
i want to be a builder because i will so many help players
My Real name is Neilivan Garcia my age is 10 years old
i will banned the troublemakers 30 minutes
yes/no but i have close freinds he/she
im Single
i will stay online everyday
yes im freindly
i will build in creative is a beutiful city

**Comment by Neil09to** [comment]
kaoru

**Comment by Neil09to** [comment]
delete commen ba?

**Comment by kylecabarle** [comment]
name:akdn
i am applying to be a helper
my reason of applying to be a helper is to help anyone that needs help
im 13 years old my real name is kyle cabarle
if there`s a troublemaker im going to ban them until they learn not to bully anyone
im going to be always online when im a helper because someone needs help
yeah im friendly

**Comment by Bernadette23** [comment]
Name:Stephany
i am applying for a builder
my reason of applying to be a builder is to help others
and my age is 9 my real name is Stephany
and if there is a hacker or they are bullying other player i will ban there until they learn why im banning he/she
and im standing always online 
i am a friendly

**Comment by Bernadette23** [comment]
Can i be a Builder?

**Comment by PixelDigits21** [comment]
-Name/Ign:PixelDigits21

-What Rank are you applying for? (3 Builders): I would like to apply as a builder as well please

-Reason :Because I like to build things, although I used to focus more on command blocks I now focus more on building

-Do you have experience on being a staff?: Yes, I had a friend once, I met him on facebook, and he was assigning server staff for his newly made server, and I was assigned as a moderator, I would kick anyone who would not apologize to any players that they have offended theirselves, sadly the server died after two years due to funding issues.

[More Information]

-Tell us about Yourself : (please add your age, name): My real name is Jasper Paolo Carbero Pairez, I am male, I am 14 years old(at the time I wrote this resume), and I love anime, video games and potatoes, for other pieces of my personal information please refer to my facebook account, Jasper Paolo Pairez

[Situations and Other stuff]

-What would be your action if there's a troublemaker?: I would analyze the situation first and warn that troublemaker, if he apologizes for anything wrong that he did to the server or any of the players it's fine, but if he continues to do whatever that he is doing that is causing havoc, I will be forced to kick him or her (If builders have access to kick commands) or report him to one of the online higher ranked server staff

-If he/she is a really close friend?: I will tell him or her that he should stop, if he or she doesn't listen then i will sadly be forced to kick her/him or report her/him

-Whats your status? or How long do you stay online?:I'm usually online for one or two hours a day due to my parents limiting my use of computers, but sometimes on weekends I have extended computer privileges, I'm also pretty busy on school matters but I still get to follow my usual agenda

-Are you friendly?: I don't know, well honestly I'm neutral, I'm not friendly to people who are not friendly towards me but i'm friendly to people who befriend me back :smile:

-If you are applying for Builder we will first observe your builds in creative: I won't be able to show you my actual plot because I wasn't really serious on making the mall me and my friends constructed on it and a lot of people helped each other to build it so it's technically not really "My Build" , but there's a friend of mine who has been offline for a long time, and I have building access to his plot, I'm sure he won't mind if I borrow his plot for Server Staff Application matters, and besides, He said that I can build anything I want on it :grin:
