### ISSUE TITLE
HERE STAFF APPLICATION ^^By:ByBlue

### ISSUE THREAD

**Issue by ByBlueJoshua** [PinoyLifeCraft/Pinoy-LifeCraft-Forums#44]
Name:ByBlue

What Rank are you applying for? I am Applying To Be Builder or Helper
Reason: MAPAGKAKATIWALAAN PO AKO. I want to be one not for fun (didn't literally mean for fun but I am enthusiastic about these things) and I love Making the SerVer 100% safe and 100% secure

Do you have experience on being a staff? Yes I was Experience to be a Staff in DragonCraft and Sagacraft .
 
Tell us about Yourself : My Real Name is Joshua Jones Rivera Reyes.My Age is 15 and my Birthday is on April 8 2001 I was Playing Minecraft EveryDay and i will Promise That i will Being Active Every Day. And make your Server Grow.

[Situations and Other stuff]
What would be your action if there's a troublemaker? -Depending on the [Define: sin] or the bad things the player has done. (Would always result into three/four possibilities). [Warning, Mute, Kick and Ban]

What's your status? or How long do you stay online? [My Status? I am single]I was Always Active in Playing Minecraft I was Started 10 years old playing minecraft so i want to being  a Staff Again until my Expirience Make me Smart my Playtime is 8:00 am to 4pm in WeekEnds 12pm to 10pm every WeekDays Because of SchoolTime ^^ but this summer my play time is weekend^^

If he/she is a really close friend?
-I don't have a close friend, sorry. [Having A close Friend is Dangerous :)]

Are you friendly?
Yes, I am a friendly potato and I would also help new players understand how the server works or what it does.
Note : Still "Lacking of Information?", kindly ask to me ^^
Mentions : @PinoyLifeCraft

**Comment by Kaoruuu** [comment]
Dear @ByBlueJoshua 

I am here (in an attempt) to question you an unclear thing in the content of your application.

You were right about almost everything else and did a good job for using the guide questions as recommended by us but the thing here is you made this ("If he/she is a really close friend?") question unclear.

Since, this might result uncertainties. Can you please tell us at least a situation and what will you do if the troublemaker is a close friend? (I know you copied some of my answers but do not blame me for this, I gave a specific situation where in I will give my close friend a punishment "ASSUMING" I have one) but how about you?

Sincerely,
Kaoru

**Comment by ByBlueJoshua** [comment]
if the troublemaker is my close friend i will talk to him to stop. like Doing My  Work As a Staff And said to him 'Play Fair to other players and stop doing AnyTrouble Enjoy PLC and if he continue Doing that i will Warn. BanTemp Then . BanPerm :) to him ^_^ that's all because i dont want Bad CloseFriend ^_^
